# Generated by Django 6.1 on 2026-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='firebase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
