# Generated by Django 6.1 on 2026-08-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_firebase_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
